<?php
/**
 * StripeCustomer
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 
 * Contact: 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace s4s/model;

use \ArrayAccess;

/**
 * StripeCustomer Class Doc Comment
 *
 * @category    Class */
 // @description Model description
/** 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StripeCustomer implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'StripeCustomer';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'credit_token' => 'string',
        'client_id' => 'string',
        'default_card_last4' => 'string',
        'default_exp_month' => 'int',
        'default_exp_year' => 'int'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'credit_token' => 'creditToken',
        'client_id' => 'client_id',
        'default_card_last4' => 'defaultCardLast4',
        'default_exp_month' => 'defaultExpMonth',
        'default_exp_year' => 'defaultExpYear'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'credit_token' => 'setCreditToken',
        'client_id' => 'setClientId',
        'default_card_last4' => 'setDefaultCardLast4',
        'default_exp_month' => 'setDefaultExpMonth',
        'default_exp_year' => 'setDefaultExpYear'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'credit_token' => 'getCreditToken',
        'client_id' => 'getClientId',
        'default_card_last4' => 'getDefaultCardLast4',
        'default_exp_month' => 'getDefaultExpMonth',
        'default_exp_year' => 'getDefaultExpYear'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['credit_token'] = isset($data['credit_token']) ? $data['credit_token'] : null;
        $this->container['client_id'] = isset($data['client_id']) ? $data['client_id'] : null;
        $this->container['default_card_last4'] = isset($data['default_card_last4']) ? $data['default_card_last4'] : null;
        $this->container['default_exp_month'] = isset($data['default_exp_month']) ? $data['default_exp_month'] : null;
        $this->container['default_exp_year'] = isset($data['default_exp_year']) ? $data['default_exp_year'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        return true;
    }


    /**
     * Gets credit_token
     * @return string
     */
    public function getCreditToken()
    {
        return $this->container['credit_token'];
    }

    /**
     * Sets credit_token
     * @param string $credit_token
     * @return $this
     */
    public function setCreditToken($credit_token)
    {
        $this->container['credit_token'] = $credit_token;

        return $this;
    }

    /**
     * Gets client_id
     * @return string
     */
    public function getClientId()
    {
        return $this->container['client_id'];
    }

    /**
     * Sets client_id
     * @param string $client_id
     * @return $this
     */
    public function setClientId($client_id)
    {
        $this->container['client_id'] = $client_id;

        return $this;
    }

    /**
     * Gets default_card_last4
     * @return string
     */
    public function getDefaultCardLast4()
    {
        return $this->container['default_card_last4'];
    }

    /**
     * Sets default_card_last4
     * @param string $default_card_last4
     * @return $this
     */
    public function setDefaultCardLast4($default_card_last4)
    {
        $this->container['default_card_last4'] = $default_card_last4;

        return $this;
    }

    /**
     * Gets default_exp_month
     * @return int
     */
    public function getDefaultExpMonth()
    {
        return $this->container['default_exp_month'];
    }

    /**
     * Sets default_exp_month
     * @param int $default_exp_month
     * @return $this
     */
    public function setDefaultExpMonth($default_exp_month)
    {
        $this->container['default_exp_month'] = $default_exp_month;

        return $this;
    }

    /**
     * Gets default_exp_year
     * @return int
     */
    public function getDefaultExpYear()
    {
        return $this->container['default_exp_year'];
    }

    /**
     * Sets default_exp_year
     * @param int $default_exp_year
     * @return $this
     */
    public function setDefaultExpYear($default_exp_year)
    {
        $this->container['default_exp_year'] = $default_exp_year;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


