<?php
/**
 * PricingPolicy
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * s4s-full
 *
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * PricingPolicy Class Doc Comment
 *
 * @category    Class */
 // @description Model description
/** 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PricingPolicy implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'PricingPolicy';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'upgrade' => 'string',
        'downgrade' => 'string'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'upgrade' => 'upgrade',
        'downgrade' => 'downgrade'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'upgrade' => 'setUpgrade',
        'downgrade' => 'setDowngrade'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'upgrade' => 'getUpgrade',
        'downgrade' => 'getDowngrade'
    );

    public static function getters()
    {
        return self::$getters;
    }

    const UPGRADE_NEXT_PERIOD = 'NextPeriod';
    const UPGRADE_IMMEDIATELY = 'Immediately';
    const UPGRADE_USER_CANT = 'UserCant';
    const DOWNGRADE_NEXT_PERIOD = 'NextPeriod';
    const DOWNGRADE_IMMEDIATELY = 'Immediately';
    const DOWNGRADE_USER_CANT = 'UserCant';
    

    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getUpgradeAllowableValues()
    {
        return [
            self::UPGRADE_NEXT_PERIOD,
            self::UPGRADE_IMMEDIATELY,
            self::UPGRADE_USER_CANT,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getDowngradeAllowableValues()
    {
        return [
            self::DOWNGRADE_NEXT_PERIOD,
            self::DOWNGRADE_IMMEDIATELY,
            self::DOWNGRADE_USER_CANT,
        ];
    }
    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['upgrade'] = isset($data['upgrade']) ? $data['upgrade'] : null;
        $this->container['downgrade'] = isset($data['downgrade']) ? $data['downgrade'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        $allowed_values = array("NextPeriod", "Immediately", "UserCant");
        if (!in_array($this->container['upgrade'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'upgrade', must be one of #{allowed_values}.";
        }

        $allowed_values = array("NextPeriod", "Immediately", "UserCant");
        if (!in_array($this->container['downgrade'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'downgrade', must be one of #{allowed_values}.";
        }

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        $allowed_values = array("NextPeriod", "Immediately", "UserCant");
        if (!in_array($this->container['upgrade'], $allowed_values)) {
            return false;
        }
        $allowed_values = array("NextPeriod", "Immediately", "UserCant");
        if (!in_array($this->container['downgrade'], $allowed_values)) {
            return false;
        }
        return true;
    }


    /**
     * Gets upgrade
     * @return string
     */
    public function getUpgrade()
    {
        return $this->container['upgrade'];
    }

    /**
     * Sets upgrade
     * @param string $upgrade
     * @return $this
     */
    public function setUpgrade($upgrade)
    {
        $allowed_values = array('NextPeriod', 'Immediately', 'UserCant');
        if (!in_array($upgrade, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'upgrade', must be one of 'NextPeriod', 'Immediately', 'UserCant'");
        }
        $this->container['upgrade'] = $upgrade;

        return $this;
    }

    /**
     * Gets downgrade
     * @return string
     */
    public function getDowngrade()
    {
        return $this->container['downgrade'];
    }

    /**
     * Sets downgrade
     * @param string $downgrade
     * @return $this
     */
    public function setDowngrade($downgrade)
    {
        $allowed_values = array('NextPeriod', 'Immediately', 'UserCant');
        if (!in_array($downgrade, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'downgrade', must be one of 'NextPeriod', 'Immediately', 'UserCant'");
        }
        $this->container['downgrade'] = $downgrade;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


