<?php
/**
 * GoogleTokenIdTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 
 * Contact: 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * GoogleTokenIdTest Class Doc Comment
 *
 * @category    Class */
// * @description Model description
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GoogleTokenIdTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "GoogleTokenId"
     */
    public function testGoogleTokenId()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "email_verified"
     */
    public function testPropertyEmailVerified()
    {

    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {

    }

    /**
     * Test attribute "exp"
     */
    public function testPropertyExp()
    {

    }

    /**
     * Test attribute "profile"
     */
    public function testPropertyProfile()
    {

    }

    /**
     * Test attribute "picture"
     */
    public function testPropertyPicture()
    {

    }

    /**
     * Test attribute "iat"
     */
    public function testPropertyIat()
    {

    }

    /**
     * Test attribute "sub"
     */
    public function testPropertySub()
    {

    }

    /**
     * Test attribute "at_hash"
     */
    public function testPropertyAtHash()
    {

    }

    /**
     * Test attribute "azp"
     */
    public function testPropertyAzp()
    {

    }

    /**
     * Test attribute "aud"
     */
    public function testPropertyAud()
    {

    }

    /**
     * Test attribute "hd"
     */
    public function testPropertyHd()
    {

    }

    /**
     * Test attribute "iss"
     */
    public function testPropertyIss()
    {

    }

}
