<?php
/**
 * SsPaymentApiTest
 * PHP version 5
 *
 * @category Class
 * @package  s4s
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 
 * Contact: 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace s4s;

use \s4s\Configuration;
use \s4s\ApiClient;
use \s4s\ApiException;
use \s4s\ObjectSerializer;

/**
 * SsPaymentApiTest Class Doc Comment
 *
 * @category Class
 * @package  s4s
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SsPaymentApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for paymentCustomerInfoCurrency
     *
     * .
     *
     */
    public function testPaymentCustomerInfoCurrency()
    {

    }

    /**
     * Test case for paymentCustomerInfoGet
     *
     * .
     *
     */
    public function testPaymentCustomerInfoGet()
    {

    }

    /**
     * Test case for paymentCustomerInfoHasPaymentInfo
     *
     * .
     *
     */
    public function testPaymentCustomerInfoHasPaymentInfo()
    {

    }

    /**
     * Test case for paymentCustomerInfoStripeCustomer
     *
     * .
     *
     */
    public function testPaymentCustomerInfoStripeCustomer()
    {

    }

    /**
     * Test case for paymentCustomerPaymentAdd
     *
     * .
     *
     */
    public function testPaymentCustomerPaymentAdd()
    {

    }

    /**
     * Test case for paymentCustomerPaymentCancelPatch
     *
     * .
     *
     */
    public function testPaymentCustomerPaymentCancelPatch()
    {

    }

    /**
     * Test case for paymentCustomerPaymentGetAll
     *
     * .
     *
     */
    public function testPaymentCustomerPaymentGetAll()
    {

    }

    /**
     * Test case for paymentCustomerPaymentPayPatch
     *
     * .
     *
     */
    public function testPaymentCustomerPaymentPayPatch()
    {

    }

    /**
     * Test case for paymentCustomerPaymentValues
     *
     * .
     *
     */
    public function testPaymentCustomerPaymentValues()
    {

    }

    /**
     * Test case for paymentPaymentGetAll
     *
     * .
     *
     */
    public function testPaymentPaymentGetAll()
    {

    }

}
