<?php
/**
 * SsPricingApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * s4s-full
 *
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * SsPricingApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SsPricingApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for customerBillClose
     *
     * .
     *
     */
    public function testCustomerBillClose()
    {

    }

    /**
     * Test case for customerBillGet
     *
     * .
     *
     */
    public function testCustomerBillGet()
    {

    }

    /**
     * Test case for customerBillInitGet
     *
     * .
     *
     */
    public function testCustomerBillInitGet()
    {

    }

    /**
     * Test case for customerBillInitPost
     *
     * .
     *
     */
    public function testCustomerBillInitPost()
    {

    }

    /**
     * Test case for customerBillOrGet
     *
     * .
     *
     */
    public function testCustomerBillOrGet()
    {

    }

    /**
     * Test case for customerBillValues
     *
     * .
     *
     */
    public function testCustomerBillValues()
    {

    }

    /**
     * Test case for customerHistoryPlanValues
     *
     * .
     *
     */
    public function testCustomerHistoryPlanValues()
    {

    }

    /**
     * Test case for customerPlanAdd
     *
     * .
     *
     */
    public function testCustomerPlanAdd()
    {

    }

    /**
     * Test case for customerPlanAddCheck
     *
     * .
     *
     */
    public function testCustomerPlanAddCheck()
    {

    }

    /**
     * Test case for customerPlanClose
     *
     * .
     *
     */
    public function testCustomerPlanClose()
    {

    }

    /**
     * Test case for customerPlanFamily
     *
     * .
     *
     */
    public function testCustomerPlanFamily()
    {

    }

    /**
     * Test case for customerPlanGet
     *
     * .
     *
     */
    public function testCustomerPlanGet()
    {

    }

    /**
     * Test case for customerPlanGetAll
     *
     * .
     *
     */
    public function testCustomerPlanGetAll()
    {

    }

    /**
     * Test case for customerPlanPay
     *
     * .
     *
     */
    public function testCustomerPlanPay()
    {

    }

    /**
     * Test case for customerPlanPlan
     *
     * .
     *
     */
    public function testCustomerPlanPlan()
    {

    }

    /**
     * Test case for customerPlanValues
     *
     * .
     *
     */
    public function testCustomerPlanValues()
    {

    }

    /**
     * Test case for pricing
     *
     * .
     *
     */
    public function testPricing()
    {

    }

    /**
     * Test case for pricing2
     *
     * .
     *
     */
    public function testPricing2()
    {

    }

    /**
     * Test case for pricingConfigGet
     *
     * .
     *
     */
    public function testPricingConfigGet()
    {

    }

    /**
     * Test case for pricingConfigPut
     *
     * .
     *
     */
    public function testPricingConfigPut()
    {

    }

    /**
     * Test case for pricingUiConf
     *
     * .
     *
     */
    public function testPricingUiConf()
    {

    }

    /**
     * Test case for pricingUiConfigGet
     *
     * .
     *
     */
    public function testPricingUiConfigGet()
    {

    }

    /**
     * Test case for pricingUiConfigPut
     *
     * .
     *
     */
    public function testPricingUiConfigPut()
    {

    }

}
