<?php
/**
 * SsUserApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * s4s-full
 *
 * description
 *
 * OpenAPI spec version: stable
 * Contact: rui.p.oliveira@impactinglabs.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * SsUserApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SsUserApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for accountAdd
     *
     * .
     *
     */
    public function testAccountAdd()
    {

    }

    /**
     * Test case for accountAutoLogin
     *
     * .
     *
     */
    public function testAccountAutoLogin()
    {

    }

    /**
     * Test case for accountChangePasswordPatch
     *
     * .
     *
     */
    public function testAccountChangePasswordPatch()
    {

    }

    /**
     * Test case for accountGetAll
     *
     * .
     *
     */
    public function testAccountGetAll()
    {

    }

    /**
     * Test case for accountIdGet
     *
     * .
     *
     */
    public function testAccountIdGet()
    {

    }

    /**
     * Test case for accountIdKeysAdd
     *
     * .
     *
     */
    public function testAccountIdKeysAdd()
    {

    }

    /**
     * Test case for accountIdKeysDel
     *
     * .
     *
     */
    public function testAccountIdKeysDel()
    {

    }

    /**
     * Test case for accountIdKeysGetAll
     *
     * .
     *
     */
    public function testAccountIdKeysGetAll()
    {

    }

    /**
     * Test case for accountIdPrivateDataPut
     *
     * .
     *
     */
    public function testAccountIdPrivateDataPut()
    {

    }

    /**
     * Test case for accountIdPut
     *
     * .
     *
     */
    public function testAccountIdPut()
    {

    }

    /**
     * Test case for accountIdStatusPut
     *
     * .
     *
     */
    public function testAccountIdStatusPut()
    {

    }

    /**
     * Test case for accountIdUserAdd
     *
     * .
     *
     */
    public function testAccountIdUserAdd()
    {

    }

    /**
     * Test case for accountIdUserChangePwdToken
     *
     * .
     *
     */
    public function testAccountIdUserChangePwdToken()
    {

    }

    /**
     * Test case for accountIdUserGet
     *
     * .
     *
     */
    public function testAccountIdUserGet()
    {

    }

    /**
     * Test case for accountIdUserLogin
     *
     * .
     *
     */
    public function testAccountIdUserLogin()
    {

    }

    /**
     * Test case for accountIdUserPut
     *
     * .
     *
     */
    public function testAccountIdUserPut()
    {

    }

    /**
     * Test case for accountIdUserResendEmailConfirmation
     *
     * .
     *
     */
    public function testAccountIdUserResendEmailConfirmation()
    {

    }

    /**
     * Test case for accountLogin
     *
     * .
     *
     */
    public function testAccountLogin()
    {

    }

    /**
     * Test case for accountLoginOrAdd
     *
     * .
     *
     */
    public function testAccountLoginOrAdd()
    {

    }

    /**
     * Test case for accountRecover
     *
     * .
     *
     */
    public function testAccountRecover()
    {

    }

    /**
     * Test case for accountUserChangePwdToken
     *
     * .
     *
     */
    public function testAccountUserChangePwdToken()
    {

    }

    /**
     * Test case for accountUserGet
     *
     * .
     *
     */
    public function testAccountUserGet()
    {

    }

    /**
     * Test case for accountUserLogin
     *
     * .
     *
     */
    public function testAccountUserLogin()
    {

    }

    /**
     * Test case for accountUserPut
     *
     * .
     *
     */
    public function testAccountUserPut()
    {

    }

    /**
     * Test case for accountUserResendEmailConfirmation
     *
     * .
     *
     */
    public function testAccountUserResendEmailConfirmation()
    {

    }

    /**
     * Test case for accountUsernameChangePwdToken
     *
     * .
     *
     */
    public function testAccountUsernameChangePwdToken()
    {

    }

    /**
     * Test case for accountUsernameGet
     *
     * .
     *
     */
    public function testAccountUsernameGet()
    {

    }

    /**
     * Test case for accountUsernameLogin
     *
     * .
     *
     */
    public function testAccountUsernameLogin()
    {

    }

    /**
     * Test case for accountUsernamePut
     *
     * .
     *
     */
    public function testAccountUsernamePut()
    {

    }

    /**
     * Test case for accountUsernameResendEmailConfirmation
     *
     * .
     *
     */
    public function testAccountUsernameResendEmailConfirmation()
    {

    }

    /**
     * Test case for authenticate
     *
     * .
     *
     */
    public function testAuthenticate()
    {

    }

    /**
     * Test case for config
     *
     * .
     *
     */
    public function testConfig()
    {

    }

    /**
     * Test case for googleLogin
     *
     * .
     *
     */
    public function testGoogleLogin()
    {

    }

    /**
     * Test case for htmlConf
     *
     * .
     *
     */
    public function testHtmlConf()
    {

    }

    /**
     * Test case for selfAccountGet
     *
     * .
     *
     */
    public function testSelfAccountGet()
    {

    }

    /**
     * Test case for selfAccountKeysAdd
     *
     * .
     *
     */
    public function testSelfAccountKeysAdd()
    {

    }

    /**
     * Test case for selfAccountKeysDel
     *
     * .
     *
     */
    public function testSelfAccountKeysDel()
    {

    }

    /**
     * Test case for selfAccountKeysGetAll
     *
     * .
     *
     */
    public function testSelfAccountKeysGetAll()
    {

    }

    /**
     * Test case for selfAccountPrivateDataPut
     *
     * .
     *
     */
    public function testSelfAccountPrivateDataPut()
    {

    }

    /**
     * Test case for selfAccountPut
     *
     * .
     *
     */
    public function testSelfAccountPut()
    {

    }

    /**
     * Test case for selfAccountStatusPut
     *
     * .
     *
     */
    public function testSelfAccountStatusPut()
    {

    }

    /**
     * Test case for selfAccountUserAdd
     *
     * .
     *
     */
    public function testSelfAccountUserAdd()
    {

    }

    /**
     * Test case for selfAccountUserChangePwdToken
     *
     * .
     *
     */
    public function testSelfAccountUserChangePwdToken()
    {

    }

    /**
     * Test case for selfAccountUserGet
     *
     * .
     *
     */
    public function testSelfAccountUserGet()
    {

    }

    /**
     * Test case for selfAccountUserLogin
     *
     * .
     *
     */
    public function testSelfAccountUserLogin()
    {

    }

    /**
     * Test case for selfAccountUserPut
     *
     * .
     *
     */
    public function testSelfAccountUserPut()
    {

    }

    /**
     * Test case for selfAccountUserResendEmailConfirmation
     *
     * .
     *
     */
    public function testSelfAccountUserResendEmailConfirmation()
    {

    }

    /**
     * Test case for selfUserChangePwdToken
     *
     * .
     *
     */
    public function testSelfUserChangePwdToken()
    {

    }

    /**
     * Test case for selfUserGet
     *
     * .
     *
     */
    public function testSelfUserGet()
    {

    }

    /**
     * Test case for selfUserLogin
     *
     * .
     *
     */
    public function testSelfUserLogin()
    {

    }

    /**
     * Test case for selfUserPut
     *
     * .
     *
     */
    public function testSelfUserPut()
    {

    }

    /**
     * Test case for selfUserResendEmailConfirmation
     *
     * .
     *
     */
    public function testSelfUserResendEmailConfirmation()
    {

    }

    /**
     * Test case for userConfigGet
     *
     * .
     *
     */
    public function testUserConfigGet()
    {

    }

    /**
     * Test case for userConfigPut
     *
     * .
     *
     */
    public function testUserConfigPut()
    {

    }

    /**
     * Test case for userUiConfigGet
     *
     * .
     *
     */
    public function testUserUiConfigGet()
    {

    }

    /**
     * Test case for userUiConfigPut
     *
     * .
     *
     */
    public function testUserUiConfigPut()
    {

    }

}
